### ISSUE TITLE
更便捷的指定后端地址

### ISSUE THREAD

**Issue by danblaze13** [stilleshan/subweb#1]
现在需要用docker构建的方式来设置后端地址。

有没有可能改为-v 映射配置文件的方式，或者-e 配置变量的方式呢，部署起来会更便捷。

仅为提议，希望开发者采纳，谢谢！

**Comment by stilleshan** [comment]
因为前端页面需要打包才能生成,每次打包后js文件都不同,所以没法 -v 挂载.

考虑到本地用户和自定义用户,回头我弄个 -e 变量用启动脚本实现吧.

**Comment by stilleshan** [comment]
https://github.com/stilleshan/subweb/commit/5bb2743cb87cdaf14dc43576e7d0b17559b5a63a
