### ISSUE TITLE
为什么短链接链接不上，提示“短链接生成失败 请检查短链接服务是否可用”

### ISSUE THREAD

**Issue by loveu5522** [stilleshan/subweb#10]
和短链接域名有关么，我的短链https://s.love.cn:6666 是不是因为带了自定义端口导致的

**Comment by figo2002** [comment]
我这里显示是跨域的问题 CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by azxcvjj** [comment]
我也是，短链网站正常访问使用，在subweb页面点短链转换就是失败，也是跨域问题，这是要在反代配置里加header头吗？加哪呀

**Comment by azxcvjj** [comment]
> 短域名网站需要开放跨域

是在反代短域名的网站的配置里改吗

**Comment by stilleshan** [comment]
是的

**Comment by azxcvjj** [comment]
> 是的

谢谢，已解决。还有个问题，subweb页面点导航中短链接会跳转到我的短链网站，但是短链网站导航中的订阅转换是直接跳转到作者你的订阅转换网站，这个需要映射短链容器里哪个文件才能进行修改？

**Comment by stilleshan** [comment]
修改config.js挂载进去
