### ISSUE TITLE
师傅 打不开啥情况

### ISSUE THREAD

**Issue by saodis** [stilleshan/subweb#11]
```sh
docker run -d --restart always -p 10081:80 stilleshan/subweb
```
![image](https://github.com/stilleshan/subweb/assets/51149477/aebcad71-16f5-448a-8eda-a8083b72713d)

```sh
docker run -d --restart always -p 10080:80 stilleshan/subweb
```
![image](https://github.com/stilleshan/subweb/assets/51149477/8d554a11-17ff-4ec4-b8ba-9d18720882ff)
跟端口还有关系么？

**Comment by stilleshan** [comment]
排查下看下容器是否启动成功。

**Comment by saodis** [comment]
起来了，你可以试下。日志只有一行，api 是啥，没有其他日志。

Stille ***@***.***> 于2023年8月14日周一 09:47写道：

**Comment by stilleshan** [comment]
<img width="1041" alt="屏幕快照 2023-08-14 的 09 55 07 上午" src="https://github.com/stilleshan/subweb/assets/22582966/d932ad9c-dce7-4800-980f-575ca3839e55">

**Comment by saodis** [comment]
嗯 查了一下大概知道什么问题了
https://www.bleepingcomputer.com/news/security/google-chrome-blocks-port-10080-to-stop-nat-slipstreaming-attacks/

抱歉，昨天没认真看。
