### ISSUE TITLE
[Feature Request] 希望增加几个简单但是实用的小功能

### ISSUE THREAD

**Issue by qhgary** [stilleshan/subweb#14]
经过几天试用，觉得这个做成docker非常好用，放在nas上可以方便我的不同设备获取clash/quanx/surfboard等配置。
同时也很简洁，没有乱七八糟花哨不实用的功能。但在使用中也碰到一些不便，希望能增设如下一些小功能：

1. 首页对于每一个输入框都能以环境变量的方式传入默认值。（目前是后端地址可以传入，但是其他内容，比如默认订阅链接，客户端的默认选择项，参数（比如节点排序，开启UDP等等是否默认勾选）等都需要每次手工填写。能在config.js里面修改设置默认值也可以。
  --原因：每个人的默认设置需求都不同，通过环境变量方式传入可以无需重新编译docker而便利使用。

2. 希望增加nginx监听端口的环境变量
 --原因：80端口一般都是被占用的，目前是手工修改的nginx配置文件改的端口，希望能通过环境变量自动
传入。

3. 增加一个输出返回文件的按钮，比如点击后可以将subconverter的返回内容存成文件。
  --原因：对于我们同时在nas上使用clash的人来说，这个文件可以映射到clash的目录里。

4. 希望能够增加一个本地配置文件列表选择（跟远程2选1输入），然后可以把本地的自定义配置文件传给subconverter。
  --原因：有时候远程的那些配置文件并不适合，但是自己写的配置文件好像又没有办法以参数方式传递给subconverter，如果subweb可以获取本地配置文件的url然后传递给subconverter就好了。

修改很小，希望作者考虑，非常感谢。

**Comment by stilleshan** [comment]
每个需求都要求能自定义开发难度太大。你这个需求都能算得上定制开发了。
