### ISSUE TITLE
HTTP ERROR 414

### ISSUE THREAD

**Issue by saodis** [stilleshan/subweb#15]
改ui之前，没有这个问题。现在节点多的时候，会 414
![image](https://github.com/stilleshan/subweb/assets/51149477/7783d92c-8de3-42af-98cb-4eb9343d88fc)

这两个正常
![image](https://github.com/stilleshan/subweb/assets/51149477/2074c57a-7975-4b8a-918d-058110bd3a95)

**Comment by stilleshan** [comment]
我看你提示应该是后端服务挂了吧？

**Comment by saodis** [comment]
> 我看你提示应该是后端服务挂了吧？

@stilleshan 没有，服务端正常，把节点删了一些就可以了。414 是客户端问题，URI Too Long，你 google 一下。

**Comment by stilleshan** [comment]
应该是 nginx 反代问题，直接用 ip 端口访问 subconverter,很长都能解析。
目前加了
client_header_buffer_size 512k;
large_client_header_buffers 4 512k;
也不行。回头在查下看。
