### ISSUE TITLE
自定义添加的“远程配置”无法正常显示

### ISSUE THREAD

**Issue by hjj345** [stilleshan/subweb#18]
我是用docker+加载配置文件的方式部署的，部署完了以后默认的所有功能正常，但是按照部署说明以及config.js文件内的格式，添加了其他几条远程配置，但是在订阅链接转换的页面“远程配置”下拉选项中，显示的是白色的选项，只有容器默认的2个ACL4SSR配置是能正常显示的。
希望可以修复。

**Comment by yzlyu** [comment]
不清楚问题是否解决，我也是修改config.js文件后，没有生效

**Comment by stilleshan** [comment]
能把config文件贴下吗？如果有敏感信息可以随意修改下。

**Comment by yzlyu** [comment]
作者大大回复好快呀！中秋快乐！
我刚测试了一下，可能是由于浏览器缓存导致的原因，我开启了inprivate后再次输入网址后，显示就正常了。

**Comment by yzlyu** [comment]
> 不清楚问题是否解决，我也是修改config.js文件后，没有生效

问题解决，只需要强制刷新浏览器缓存即可：
1、windowsn电脑，Ctrl + F5 或 
2、MAC，Cmd + Shift + R
