### ISSUE TITLE
不能批量复制多个节点进订阅吗

### ISSUE THREAD

**Issue by gtgc2005** [stilleshan/subweb#2]
不能批量复制多个节点进订阅吗，我试了下识别不了。只能一个个节点单独加

**Comment by stilleshan** [comment]
你是指单个节点使用 | 分割批量添加吗

**Comment by gtgc2005** [comment]
大致如此，但是如果不用|，直接能识别多行的单节点就更好了。因为都是自建的节点，以往用CareyWang/sub-web都是直接多行节点复制进去就能转换

**Comment by stilleshan** [comment]
OK 开发时没注意这个需求,下周争取更新加上该功能.

**Comment by stilleshan** [comment]
已支持 https://github.com/stilleshan/subweb/commit/3d5054182bf607ac227d4b6514cbafffa7ce0fff
