### ISSUE TITLE
分流默认配置问题

### ISSUE THREAD

**Issue by EchoHS** [stilleshan/subweb#26]
搭建了subweb + subconverter + myurls 合并进阶版，网页默认使用的是默认配置，loon转换出来的默认配置出来的分流规则网址前缀是http://127.0.0.1:25500，用其它配置就没问题，请问默认配置能在哪里修改？

**Comment by stilleshan** [comment]
conf/config.js 里修改

**Comment by EchoHS** [comment]
> conf/config.js 里修改

API URL已经修改过了，转换出来的网址能正确使用api网址，使用自定义及其他配置都可以正确使用API URL。
但默认配置在转换到loon和quanx配置时，转换后的链接可以使用API URL，但分流规则还是使用http://127.0.0.1:25500。

config.js只看到可以新增自定义分流，但网页还是有个默认配置，这个默认配置有办法删除吗？
附上截图
![image](https://github.com/user-attachments/assets/4a37cbea-197a-43e3-b368-35b31245c990)
![image](https://github.com/user-attachments/assets/586f6740-5210-4b5d-95be-a275a6baacfb)

**Comment by stilleshan** [comment]
默认配置是不在url上拼接配置文件地址的，是默认使用subconverter后端程序内的默认规则。

所以这个前端页面为了满足不同人需求，如有人只用默认内置规则，那么这个页面这里选项就是空的，就会有问题。

你的需求只能自己修改源代码打包自己的镜像。

**Comment by EchoHS** [comment]
> 默认配置是不在url上拼接配置文件地址的，是默认使用subconverter后端程序内的默认规则。
> 
> 所以这个前端页面为了满足不同人需求，如有人只用默认内置规则，那么这个页面这里选项就是空的，就会有问题。
> 
> 你的需求只能自己修改源代码打包自己的镜像。

感谢解答，修改了subconverter后端程序内pref.toml里面的配置解决了
