### ISSUE TITLE
能否支持在前端页面增加一个短链转换能力，例如https://suo.yt/

### ISSUE THREAD

**Issue by daweiyuanzhang** [stilleshan/subweb#3]
RT

**Comment by stilleshan** [comment]
有推荐的开源项目吗?之前考虑过,可以尝试接入

**Comment by daweiyuanzhang** [comment]
@stilleshan https://agwa5783.gitbook.io/sub-web/kuo-zhan-yi-myurls-duan-lian-fu-wu-da-jian/untitled 看sub-web项目是支持的，可以看下。感恩

**Comment by stilleshan** [comment]
https://github.com/stilleshan/subweb/commit/758e4621ce4d51ad6ec3b1640288a5bc0a7b59b2
