### ISSUE TITLE
是否有计划适配vercel使用环境变量部署

### ISSUE THREAD

**Issue by daweiyuanzhang** [stilleshan/subweb#4]
目前已经能在vercel部署，但是一些配置需要手动修改文件，是否可以支持环境变量进行替换

**Comment by stilleshan** [comment]
我没试过 vercel,但是说明里有变量,应该是可以用的
SITE_NAME=subweb
API_URL=https://sub.ops.ci
SHORT_URL=https://s.ops.ci

**Comment by daweiyuanzhang** [comment]
@stilleshan 现在看subweb里环境变量是通过shell脚本获取到之后进行替换，但是vercel不会执行这个替换脚本😂

**Comment by stilleshan** [comment]
有相关开发文档么? 确实没研究过 vercel 的变量...

**Comment by daweiyuanzhang** [comment]
@stilleshan 也是看到CareyWang/sub-web有用环境变量进行替换，比如https://github.com/CareyWang/sub-web/blob/945a8e774eb145ca79391d3e8cd6b8086c423b80/src/views/Subconverter.vue#L224-L230

**Comment by stilleshan** [comment]
好,这个应该没什么问题,这两天弄一下.

**Comment by stilleshan** [comment]
已经支持.注意因为 docker 和 vercel 的变量方式不同,所以单独出了 vercel 分支,具体查看 README

https://github.com/stilleshan/subweb/commit/1c7bbf576f73956c0a697cac16d332772bd80eba
