### ISSUE TITLE
能否支持环境变量指定远程配置文件

### ISSUE THREAD

**Issue by Cara-Hall** [stilleshan/subweb#7]
这款subweb十分简洁，个人非常喜欢，已经在vercel上部署使用。

因为习惯使用自定义的远程配置文件，每次都需要手动输入，

有没有可能支持环境变量指定远程配置文件，操作逻辑类似后端地址，下拉窗口有默认和自定义两种可选。感谢！

**Comment by stilleshan** [comment]
点更多参数里面有远程配置

**Comment by Cara-Hall** [comment]
> 点更多参数里面有远程配置

可能是我没有表达清楚。现在点更多参数，远程配置栏默认是空的，可选状态，即采用subconverter的默认配置。

我是想通过环境变量，指定默认的远程配置文件，同时下拉菜单可以选填自定义配置文件地址。

操作的逻辑类似后端地址栏，通过环境变量给定默认的参数，同时也支持修改。

因为每次订阅转换，都要去找自己常用的配置文件地址填进去有一点点麻烦，如果能够通过环境变量指定自己常用的配置文件为默认参数就方便很多。

**Comment by stilleshan** [comment]
已更新到 vercel 分支。增加 VUE_APP_REMOTE_CONFIG 变量。

https://github.com/stilleshan/subweb/commit/16ddc79ec3243ceb4e83dbe3aeb8495418b8b7d1

**Comment by vitaminx** [comment]
能否实现下拉菜单选项：

![image](https://raw.githubusercontent.com/vitaminx/pic/main/github/stilleshan-subweb-01.png)

需要如何修改？

**Comment by mps233** [comment]
俺也想知道 环境变量如何添加多个远程配置文件
