### ISSUE TITLE
建议加入远程规则下拉菜单选项

### ISSUE THREAD

**Issue by vitaminx** [stilleshan/subweb#9]
建议加入如下效果的远程规则下拉菜单选项

![image](https://raw.githubusercontent.com/vitaminx/pic/main/github/stilleshan-subweb-01.png)

订阅转换除了整理转换连接以外，还有一个很重要的功能就是使用各种规则，希望加入！

**Comment by g93920079** [comment]
同意，希望加入远程配置规则选项

**Comment by stilleshan** [comment]
推荐几个常用的，我加上去。

**Comment by g93920079** [comment]
我觉的可以至少保留一个ACL4SSR 标准版 和 ACL4SSR_Online FULL 版

**Comment by stilleshan** [comment]
已更新
